/**
 * JS3 - A Drawing & Tweening API for the JavaScript Canvas
 * Version : 0.1.6
 * Documentation : http://quietless.com/js3/
 *
 * Copyright 2012 Stephen Braitsch :: @braitsch
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
**/

function JS3(a){function b(){g.dx=g.mx;g.dy=g.my;for(var a=f.length-1;0<=a;a--)if(f[a].mouse&&f[a].enabled){h=f[a];f.splice(a,1);f.push(h);break}}function c(){h&&(void 0==m?h._onClick&&h._onClick(h):h._onDragComplete&&h._onDragComplete(h));h=m=void 0}function d(a){var b=0,c=0,d=e;do b+=d.offsetLeft,c+=d.offsetTop;while(d=d.offsetParent);g.mx=a.pageX-b;g.my=a.pageY-c;a=!1;for(b=f.length-1;0<=b;b--)if(f[b].mouse&&f[b].enabled){a=!0;break}window.document.body.style.cursor=a?"pointer":"default";h&&h.draggable&&
(void 0==m?(m=h,void 0!=h._onDragStart&&h._onDragStart(h)):(h.x+=g.mx-g.dx,h.y+=g.my-g.dy,g.dy=g.my,g.dx=g.mx,void 0!=h._onDragChange&&h._onDragChange(h)))}var e=document.getElementById(a),g=e.getContext("2d"),n=e.width,o=e.height,h=void 0,m=void 0,f=[],j=[],k=[],l=[],r=!0,s="#ffffff",u="My Canvas";this.__defineGetter__("width",function(){return n});this.__defineGetter__("height",function(){return o});this.__defineGetter__("numChildren",function(){return f.length});this.__defineGetter__("position",
function(){for(var a=0,b=0,c=e;null!=c;)a+=c.offsetLeft,b+=c.offsetTop,c=c.offsetParent;return{x:a,y:b}});this.__defineSetter__("drawClean",function(a){r=a});this.__defineSetter__("background",function(a){s=a;q()});this.__defineSetter__("windowTitle",function(a){u=a});this.__defineSetter__("interactive",function(a){a?(e.addEventListener("mousedown",b),e.addEventListener("mouseup",c),e.addEventListener("mousemove",d)):(e.removeEventListener("mousedown",b),e.removeEventListener("mouseup",c),e.removeEventListener("mousemove",
d))});this.addChild=function(a){a.stage=g;f.push(a)};this.addChildAt=function(a,b){b<=f.length&&f.splice(b,0,a)};this.getChildAt=function(a){return f[a]};this.getChildAtRandom=function(){return f[Math.floor(Math.random()*f.length)]};this.removeChild=function(a,b){for(var c=f.length-1;0<=c;c--)if(f[c]==a){removeChildAt(c,b);break}};this.removeChildAt=function(a,b){b&&(f[a]=null);f.splice(a,1)};this.run=function(a,b,c,d){for(var e=k.length-1;0<=e;e--)if(a==k[e].f)return;k.push({f:a,d:b,r:c,o:d,t:Date.now()})};
this.stop=function(a){v(a)};this.tween=function(a,b,c){a.isTweening||(a.isTweening=!0,a=new Tween(a,b,c),void 0==a.delay?w(a):setTimeout(w,1E3*a.delay,a))};this.clear=function(){for(;f.length;)f[0]=null,f.splice(0,1);for(;j.length;)j[0]=null,j.splice(0,1);for(;l.length;)l[0]=null,l.splice(0,1);for(;k.length;)k[0]=null,k.splice(0,1);f=[];j=[];l=[];k=[];q()};this.setSize=function(a,b){e.width=n=a;e.height=o=b};this.save=function(){var a=e.toDataURL("image/png"),b=window.open("","_blank","width="+n+
", height="+o);b.document.write('<!DOCTYPE html style="padding:0; margin:0"><head><title>'+u+"</title>");b.document.write('</head><body style="background: #f2f2f2; padding:0; margin:0">');b.document.write('<img src="'+a+'"/>');b.document.write("</body></html>");b.document.close()};this.drawLine=function(a){a.stage=g;j.push(new JS3Line(a))};this.drawArc=function(a){a.stage=g;j.push(new JS3Arc(a))};this.drawRect=function(a){a.stage=g;j.push(new JS3Rect(a))};this.drawCircle=function(a){a.stage=g;j.push(new JS3Circle(a))};
this.drawTri=function(a){a.stage=g;j.push(new JS3Tri(a))};this.drawText=function(a){a.stage=g;j.push(new JS3Text(a))};var q=function(){g.fillStyle=s;g.fillRect(0,0,n,o)},w=function(a){a.start=Date.now();l.push(a)},v=function(a){for(var b=k.length-1;0<=b;b--)a==k[b].f&&k.splice(b,1)};JS3.func.push(function(){for(var a=0;a<l.length;a++){t=l[a];if(0==t.elapsed&&void 0!=t.onStart)t.onStart();t.elapsed=Date.now()-t.start;for(p in t.props)t.object[p]=t.easeFunc(t.elapsed,t.props[p].a,t.props[p].b,t.duration);
if(t.elapsed>=t.duration){l.splice(a,1);t.object.isTweening=!1;for(p in t.props)t.object[p]=t.props[p].a+t.props[p].b;if(void 0!=t.onComplete)t.onComplete()}}for(var a=Date.now(),b=0;b<k.length;b++){var c=k[b];if(void 0===c.d||a-c.t>1E3*c.d)c.f(),c.t=a,void 0!=c.r&&(c.r--,0==c.r&&(v(c.f),void 0!=c.o&&c.o()))}r&&q();for(i=0;i<f.length;)a=f[i],a.update(a),i++;for(;j.length;)a=j[0],a.update(a),j.splice(0,1)})}JS3.getRandomColor=function(){return"#"+Math.round(16777215*Math.random()).toString(16)};
JS3.getRandomValue=function(a,b){return void 0==a?Math.random():void 0==b?Math.random()*a:Math.random()*(b-a)+a};JS3.drawLine=function(a){a.cx=(a.x1+a.x2)/2;a.cy=(a.y1+a.y2)/2;JS3.openShape(a);a.stage.moveTo(a.x1-a.cx,a.y1-a.cy);a.stage.lineTo(a.x2-a.cx,a.y2-a.cy);JS3.drawShape(a)};
JS3.drawArc=function(a){a.cx=(a.x1+a.x2)/2;a.cy=(a.y1+a.y2)/2;JS3.openShape(a);a.stage.moveTo(a.x1-a.cx,a.y1-a.cy);a.stage.quadraticCurveTo(a.xc-a.cx,a.yc-a.cy,a.x2-a.cx,a.y2-a.cy);a.mouse=a.stage.isPointInPath(a.stage.mx,a.stage.my);JS3.stroke(a);a.stage.restore()};JS3.drawRect=function(a){JS3.getCntrPt(a);JS3.openShape(a);a.stage.rect(-a.cx,-a.cy,2*a.cx,2*a.cy);JS3.drawShape(a)};
JS3.drawCirc=function(a){JS3.getCntrPt(a);var b=0.5522848*a.cx,c=0.5522848*a.cy;JS3.openShape(a);a.stage.moveTo(-a.cx,0);a.stage.bezierCurveTo(-a.cx,-c,-b,-a.cy,0,-a.cy);a.stage.bezierCurveTo(b,-a.cy,a.cx,-c,a.cx,0);a.stage.bezierCurveTo(a.cx,c,b,a.cy,0,a.cy);a.stage.bezierCurveTo(-b,a.cy,-a.cx,c,-a.cx,0);JS3.drawShape(a)};
JS3.drawTri=function(a){a.width==a.height?JS3.drawEquilateral(a):JS3.drawCustomTriangle(a);JS3.openShape(a);a.stage.moveTo(a.x1,a.y1);a.stage.lineTo(a.x2,a.y2);a.stage.lineTo(a.x3,a.y3);a.stage.lineTo(a.x1,a.y1);JS3.drawShape(a)};JS3.drawEquilateral=function(a){var b=a.width,c=a.height*(Math.sqrt(3)/2);a.x1=0;a.y1=-2*c/3;a.x2=b/2;a.y2=c/3;a.x3=-b/2;a.y3=c/3;a.cx=b/2;a.cy=c/2+c/2/3};
JS3.drawCustomTriangle=function(a){var b=a.width,c=a.height;a.x1=a.x1||0;a.y1=a.y1||-c/2;a.x2=a.x2||b/2;a.y2=a.y2||c/2;a.x3=a.x3||-b/2;a.y3=a.y3||c/2;a.cx=b/2;a.cy=c/2};JS3.drawImage=function(a){!1!=a.image.src&&(a.cx=a.image.width/2,a.cy=a.image.height/2,JS3.openShape(a),a.stage.rect(-a.cx,-a.cy,2*a.cx,2*a.cy),a.stage.drawImage(a.image,-a.cx,-a.cy),JS3.drawShape(a))};
JS3.drawText=function(a){var b=a.bold?"Bold ":"",b=b+(a.italic?"Italic ":"");a.stage.font=b+a.size+"pt "+a.font;a.stage.textAlign="left";a.stage.textBaseline="top";a.cy=JS3getTextHeight(a)/2;a.cx=a.stage.measureText(a.text).width/2;JS3.openShape(a);a.fill&&JS3.fill(a);a.stroke&&JS3.stroke(a);JS3.drawShape(a)};
JS3.fill=function(a){a.stage.globalAlpha=a.alpha*a.fillAlpha;a.stage.fillStyle=a.color||a.fillColor;a instanceof JS3Text?a.stage.fillText(a.text,-a.cx,-a.cy):a.stage.fill();a.stage.globalAlpha=1};JS3.stroke=function(a){a.stage.globalAlpha=a.alpha*a.strokeAlpha;a.stage.lineCap=a.capStyle;a.stage.lineWidth=a.strokeWidth;a.stage.strokeStyle=a.strokeColor;a instanceof JS3Text?a.stage.strokeText(a.text,-a.cx,-a.cy):a.stage.stroke();a.stage.globalAlpha=1};
JS3.getCntrPt=function(a){a.cx=a.width/2||a.size/2;a.cy=a.height/2||a.size/2};JS3.openShape=function(a){a.stage.save();a.stage.globalAlpha=a.alpha;a.stage.translate(a.x+a.cx,a.y+a.cy);a.stage.scale(a.scaleX,a.scaleY);a.stage.rotate(a.rotation*Math.PI/180);a.stage.beginPath()};JS3.drawShape=function(a){a.stage.closePath();a.mouse=a.stage.isPointInPath(a.stage.mx,a.stage.my);a.fill&&JS3.fill(a);a.stroke&&JS3.stroke(a);a.stage.restore()};JS3.copyProps=function(a,b){for(var c in a)b[c]=a[c]};
linear=function(a,b,c,d){return c*a/d+b};easeInQuad=function(a,b,c,d){a/=d;return c*a*a+b};easeOutQuad=function(a,b,c,d){a/=d;return-c*a*(a-2)+b};easeInOutQuad=function(a,b,c,d){a/=d/2;if(1>a)return c/2*a*a+b;a--;return-c/2*(a*(a-2)-1)+b};easeInCubic=function(a,b,c,d){a/=d;return c*a*a*a+b};easeOutCubic=function(a,b,c,d){a/=d;a--;return c*(a*a*a+1)+b};easeInOutCubic=function(a,b,c,d){a/=d/2;if(1>a)return c/2*a*a*a+b;a-=2;return c/2*(a*a*a+2)+b};
easeInQuart=function(a,b,c,d){a/=d;return c*a*a*a*a+b};easeOutQuart=function(a,b,c,d){a/=d;a--;return-c*(a*a*a*a-1)+b};easeInOutQuart=function(a,b,c,d){a/=d/2;if(1>a)return c/2*a*a*a*a+b;a-=2;return-c/2*(a*a*a*a-2)+b};easeInQuint=function(a,b,c,d){a/=d;return c*a*a*a*a*a+b};easeOutQuint=function(a,b,c,d){a/=d;a--;return c*(a*a*a*a*a+1)+b};easeInOutQuint=function(a,b,c,d){a/=d/2;if(1>a)return c/2*a*a*a*a*a+b;a-=2;return c/2*(a*a*a*a*a+2)+b};
easeInSine=function(a,b,c,d){return-c*Math.cos(a/d*(Math.PI/2))+c+b};easeOutSine=function(a,b,c,d){return c*Math.sin(a/d*(Math.PI/2))+b};easeInOutSine=function(a,b,c,d){return-c/2*(Math.cos(Math.PI*a/d)-1)+b};easeInExpo=function(a,b,c,d){return c*Math.pow(2,10*(a/d-1))+b};easeOutExpo=function(a,b,c,d){return c*(-Math.pow(2,-10*a/d)+1)+b};easeInOutExpo=function(a,b,c,d){a/=d/2;if(1>a)return c/2*Math.pow(2,10*(a-1))+b;a--;return c/2*(-Math.pow(2,-10*a)+2)+b};
easeInCirc=function(a,b,c,d){a/=d;return-c*(Math.sqrt(1-a*a)-1)+b};easeOutCirc=function(a,b,c,d){a/=d;a--;return c*Math.sqrt(1-a*a)+b};easeInOutCirc=function(a,b,c,d){a/=d/2;if(1>a)return-c/2*(Math.sqrt(1-a*a)-1)+b;a-=2;return c/2*(Math.sqrt(1-a*a)+1)+b};JS3.func=[];JS3.loop=function(){JS3.getFrameRate();for(var a=0;a<JS3.func.length;a++)JS3.func[a]();window.getAnimFrame(JS3.loop)};
window.getAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();JS3.getFrameRate=function(){var a=window.mozAnimationStartTime||Date.now();5<a-JS3.FT&&(JS3.FR=1E3/(a-JS3.FT),JS3.FT=a)};
JS3.showFrameRate=function(a,b,c){if(!document.getElementById("JS3FR")){var d=0;yy=0;c&&(d=c.position.x,yy=c.position.y);a&&(d+=a);b&&(yy+=b);var e=document.createElement("div");e.setAttribute("id","JS3FR");e.style.position="absolute";e.style.left=d+"px";e.style.top=yy+"px";e.style.background="#333";e.style.border="1px solid #555";e.style.color="#00ff00";e.style.padding="10px";e.style.fontSize="16px";e.style.fontFamily="Arial,sans-serif";e.style.textShadow="1px 1px 0 #000";e.innerHTML="60.0 fps";
document.body.appendChild(e);setInterval(function(){var a=JS3.FR.toFixed(1);e.innerHTML=a+" fps";e.style.color=a<15?"#ff0000":a>=15&&a<=30?"#ffff00":"#00ff00"},1E3)}};JS3.FR=0;JS3.FT=Date.now()-1;window.getAnimFrame(JS3.loop);function JS3Line(a){JS3getBaseProps(this);JS3getLineProps(this);this.update=JS3.drawLine;a&&JS3.copyProps(a,this)}function JS3Arc(a){JS3getBaseProps(this);JS3getLineProps(this);this.update=JS3.drawArc;a&&JS3.copyProps(a,this)}
function JS3Tri(a){JS3getBaseProps(this);this.update=JS3.drawTri;a&&JS3.copyProps(a,this);this.p1={};this.p2={};this.p3={}}function JS3Rect(a){JS3getBaseProps(this);this.update=JS3.drawRect;a&&JS3.copyProps(a,this)}function JS3Circle(a){JS3getBaseProps(this);this.update=JS3.drawCirc;a&&JS3.copyProps(a,this)}function JS3Text(a){JS3getBaseProps(this);JS3getTextProps(this);this.update=JS3.drawText;a&&JS3.copyProps(a,this)}
function JS3Image(a){JS3getBaseProps(this);JS3getImageProps(this);this.update=JS3.drawImage;this.fill=this.stroke=!1;a&&JS3.copyProps(a,this)}
function JS3getBaseProps(a){a.__defineGetter__("size",function(){return a._size});a.__defineSetter__("size",function(b){a._size=a.width=a.height=b});a.__defineSetter__("click",function(b){a._onClick=b;a.enabled=!0});a.__defineGetter__("draggable",function(){return a._draggable});a.__defineSetter__("draggable",function(b){a._draggable=b;!0==b&&(a.enabled=!0)});a.__defineSetter__("drag",function(b){a._onDragChange=b;a.draggable=!0});a.__defineSetter__("dragStart",function(b){a._onDragStart=b;a.draggable=
!0});a.__defineSetter__("dragComplete",function(b){a._onDragComplete=b;a.draggable=!0});a.x=a.y=a.rotation=0;a._size=25;a.fillColor="#ddd";a.strokeColor="#ccc";a.fill=a.stroke=!0;a.alpha=a.scaleX=a.scaleY=a.fillAlpha=a.strokeAlpha=1;a.strokeWidth=2}function JS3getLineProps(a){a.capStyle="butt";a.x1=a.y1=a.cx=a.cy=a.x2=a.y2=0;a.__defineSetter__("color",function(b){a.strokeColor=b});a.__defineSetter__("thickness",function(b){a.strokeWidth=b})}
function JS3getImageProps(a){a.image=new Image;a.__defineSetter__("src",function(b){a.image.src=b});a.__defineSetter__("ready",function(b){a.image.onload=b});a.__defineGetter__("width",function(){return a.image.width});a.__defineGetter__("height",function(){return a.image.height})}function JS3getTextProps(a){a.size=12;a.font="Arial";a.color="#333";a.stroke=a.bold=a.italic=!1}
function JS3getTextHeight(a){var b=document.getElementsByTagName("body")[0],c=document.createElement("div");c.appendChild(document.createTextNode("M"));c.setAttribute("style","font-family:"+a.font+"; font-size:"+a.size+"pt; line-height:normal");b.appendChild(c);a=c.offsetHeight;b.removeChild(c);return a}
function Tween(a,b,c){this.object=a;this.duration=1E3*b;this.delay=c.delay;this.elapsed=this.start=0;this.onStart=c.onStart;this.onComplete=c.onComplete;this.easeFunc=c.ease||linear;this.props={};for(var d in c)isNumber(c[d])&&(this.props[d]={a:a[d],b:c[d]-a[d]})}var trace=function(a){try{console.log(a)}catch(b){}},isNumber=function(a){return!isNaN(parseFloat(a))&&isFinite(a)};